buckets:
  clean: fcst-clean-prod
  refined: fcst-refined-demand-forecast-prod
paths:
  clean_datalake: datalake/
  refined_global: global/
Tables:
  transactions: "fcst_clean_prod.f_transaction_detail"
  deliveries: "fcst_clean_prod.f_delivery_detail"
functional_parameters:
  first_historical_week: 201507
  first_backtesting_cutoff: 201924
  list_puch_org:
  - Z001
  - Z002
  - Z003
  - Z004
  - Z005
  - Z006
  - Z008
  - Z011
  - Z012
  - Z013
  - Z017
  - Z019
  - Z022
  - Z025
  - Z026
  - Z027
  - Z028
  - Z042
  - Z060
  - Z061
  - Z065
  - Z066
  - Z078
  - Z091
  - Z093
  - Z094
  - Z095
  - Z096
  - Z098
  - Z101
  - Z102
  - Z104
  - Z105
  - Z106
  - Z107
  - Z112
  - Z115
technical_parameters:
    spark_conf:
        spark.yarn.isPython : "true"
        spark.serializer : "org.apache.spark.serializer.KryoSerializer"
        spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version : 2
        spark.maximizeResourceAllocation : "false"
        spark.dynamicAllocation.enabled : "false"
        spark.executor.cores : 5
        spark.executor.memory : "36g"
        spark.executor.memoryOverhead : "4g"
        spark.executor.instances : 8
        spark.default.parallelism : 80
        spark.sql.shuffle.partitions : 80
        spark.yarn.am.cores : 5
        spark.yarn.am.memory : "36g"
        spark.yarn.am.memoryOverhead : "4g"
        hive.exec.dynamic.partition.mode: nonstrict