buckets:
  clean: fcst-clean-prod
  refined: fcst-workspace/forecast-cn/fcst-refined-demand-forecast-dev
paths:
  clean_datalake: datalake/
  refined_global: global/
functional_parameters:
  first_historical_week: 201601
  first_backtesting_cutoff: 201925
  list_purch_org:
    - Z001
    - Z008
    - Z042
    - Z066
    - Z078
    - Z098Ëš
    - Z107
technical_parameters:
  spark_conf:
    spark.yarn.isPython: "true"
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"
    spark.sql.legacy.parquet.int96RebaseModeInRead: "CORRECTED"
    spark.sql.legacy.parquet.datetimeRebaseModeInWrite: "CORRECTED"
    spark.sql.legacy.parquet.datetimeRebaseModeInRead: "CORRECTED"
    spark.sql.legacy.timeParserPolicy": "LEGACY"
