buckets:
  clean: fcst-clean-prod
  refined: fcst-refined-demand-forecast-dev
paths:
  clean_datalake: datalake/
  refined_global: global/
functional_parameters:
  first_historical_week: 201507
  first_backtesting_cutoff: 201924
  list_puch_org:
  - Z001
  - Z002
  - Z003
  - Z004
  - Z005
  - Z006
  - Z011
  - Z012
  - Z013
  - Z017
  - Z019
  - Z022
  - Z025
  - Z026
  - Z027
  - Z028
  - Z060
  - Z061
  - Z065
  - Z091
  - Z093
  - Z094
  - Z095
  - Z096
  - Z102
  - Z104
  - Z105
  - Z106
  - Z112
  - Z115
technical_parameters:
    spark_conf:
        spark.maximizeResourceAllocation : "false"
        spark.dynamicAllocation.enabled : "false"
        spark.executors.cores : 5
        spark.executor.memory : "3g"
        spark.executor.memoryOverhead : "1g"
        spark.executor.instances : 8
        spark.default.parallelism : 80
        spark.sql.shuffle.partitions : 80
        spark.yarn.am.cores : 5
        spark.yarn.am.memory : "3g"
        spark.yarn.am.memoryOverhead : "1g"
    

