buckets:
  clean: fcst-clean-prod
  refined: fcst-workspace
paths:
  clean_datalake: datalake/
  refined_global: forecast-cn/fcst-refined-demand-forecast-dev/test_data/
  but_num: forecastcn/fcst-data-exchange-dev/dashboard/tableau/raw/
functional_parameters:
  but_week_range:
    - 202101
    - 202153
  first_historical_week: 201601
  first_backtesting_cutoff: 201901
  list_purch_org:
    - Z015
    - Z024
    - Z067
    - Z069
    - Z108
technical_parameters:
  spark_conf:
    spark.yarn.isPython: "true"
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"
    spark.sql.legacy.parquet.int96RebaseModeInRead: "CORRECTED"
    spark.sql.legacy.parquet.datetimeRebaseModeInWrite: "CORRECTED"
    spark.sql.legacy.parquet.datetimeRebaseModeInRead: "CORRECTED"
    spark.sql.legacy.timeParserPolicy: "LEGACY"
    spark.driver.maxResultSize: 8g

