buckets:
  clean: fcst-clean-dev
  refined: fcst-refined-demand-forecast-dev
paths:
  clean_datalake: datalake/
  refined_global: global/
Tables:
  schema: "fcst_clean_dev"
functional_parameters:
  first_historical_week: 201601
  first_backtesting_cutoff: 201925
  lifestage_data_first_hist_week: 201918
  max_nb_soldout_weeks_for_hist: 4
  list_purch_org:
  - Z001
  - Z008
  - Z042
  - Z066
  - Z078
  - Z098
  - Z107
technical_parameters:
    spark_conf:
        spark.yarn.isPython : "true"
        spark.serializer : "org.apache.spark.serializer.KryoSerializer"
        spark.sql.legacy.parquet.int96RebaseModeInRead : "CORRECTED"
        spark.sql.legacy.parquet.datetimeRebaseModeInWrite : "CORRECTED"
        spark.sql.legacy.parquet.datetimeRebaseModeInRead : "CORRECTED"
        spark.sql.legacy.timeParserPolicy" : "LEGACY"
